// js/upload.js

// Ensure user is logged in before allowing uploads
checkAuth(true);

async function uploadPost() {
  const alertBox = document.getElementById('upload-alert');
  const fileInput = document.getElementById('post-file');
  const caption = document.getElementById('post-caption').value.trim();
  const description = document.getElementById('post-desc').value.trim();

  // 1. Validate if a file is selected
  if (!fileInput.files[0]) {
    alertBox.style.color = '#ed4956';
    return alertBox.innerText = 'Please select a video or image file.';
  }

  alertBox.style.color = '#262626';
  alertBox.innerText = 'Step 1: Requesting secure upload signature...';

  try {
    const file = fileInput.files[0];

    // STEP 1: Get signature from your backend (GET request)
    const signatureResponse = await fetch(`${BASE_URL}/post/upload-post`, getFetchOptions('GET'));
    const signatureData = await signatureResponse.json();

    if (!signatureResponse.ok || !signatureData.success) {
      alertBox.style.color = '#ed4956';
      return alertBox.innerText = 'Failed to get upload signature from server.';
    }

    // Extract the Cloudinary details generated by your backend
    const { signature, timestamp, cloudName, apiKey, folder, public_id } = signatureData.data;

    alertBox.innerText = 'Step 2: Uploading media directly to Cloudinary...';

    // STEP 2: Upload directly to Cloudinary API
    const cloudinaryData = new FormData();
    cloudinaryData.append('file', file);
    cloudinaryData.append('api_key', apiKey);
    cloudinaryData.append('timestamp', timestamp);
    cloudinaryData.append('signature', signature);
    cloudinaryData.append('folder', folder);
    cloudinaryData.append('public_id', public_id);

    // Determine if we are uploading a video or an image to hit the correct Cloudinary endpoint
    const resourceType = file.type.startsWith('video/') ? 'video' : 'image';
    const cloudinaryUrl = `https://api.cloudinary.com/v1_1/${cloudName}/${resourceType}/upload`;

    const uploadResponse = await fetch(cloudinaryUrl, {
      method: 'POST',
      body: cloudinaryData 
      // Note: We do not use getFetchOptions() here because Cloudinary does not need our backend tokens
    });

    const uploadedFile = await uploadResponse.json();

    if (uploadedFile.error) {
       alertBox.style.color = '#ed4956';
       return alertBox.innerText = 'Cloudinary upload failed: ' + uploadedFile.error.message;
    }

    alertBox.innerText = 'Step 3: Saving post to database...';

    // STEP 3: Create Post in Database using your backend route
    const postUrl = uploadedFile.secure_url;
    
    const createResponse = await fetch(`${BASE_URL}/post/create-post`, getFetchOptions('POST', {
      postUrl,
      public_id: uploadedFile.public_id,
      caption,
      description
    }));
    
    if (createResponse.ok) {
      alertBox.style.color = 'green';
      alertBox.innerText = 'Post created successfully!';
      
      // Clear the form
      fileInput.value = '';
      document.getElementById('post-caption').value = '';
      document.getElementById('post-desc').value = '';
      
      // Redirect to feed after a short delay
      setTimeout(() => { window.location.href = 'feed.html'; }, 1000);
    } else {
      alertBox.style.color = '#ed4956';
      alertBox.innerText = 'Failed to save post details to the database.';
    }
  } catch (err) {
    alertBox.style.color = '#ed4956';
    alertBox.innerText = 'Network error while uploading.';
    console.error('Upload Error:', err);
  }
}